/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const stores_Logic = require('./code/stores-logic');

class zfullSrv extends LCAPApplicationService {
    async init() {

        this.before(['READ', 'UPDATE'], 'Stores', async (request) => {
            await stores_Logic(request);
        });

        return super.init();
    }
}


module.exports = {
    zfullSrv
};